services:
  pico2-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pico2-server
    restart: unless-stopped
    volumes:
      - .:/workspace
    ports:
      - "8001:8001"
    working_dir: /workspace
    environment:
      - RUST_LOG=info
      - CARGO_TARGET_DIR=/build
      - SERVER_PORT=8001
      - SERVER_IP=0.0.0.0
      - SERVER_STATIC_DIR=/workspace/web/dist
      - SERVER_DATA_DIR=/workspace/data
    command: ["sh", "-c", "cargo run --release --bin server"]
